[project]
name = "send-tele-message"
version = "0.1.0"
description = "A telegram bot for sending message from console."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pytelegrambotapi>=4.27.0",
]

[dependency-groups]
dev = [
    "nuitka>=2.7.12",
]
